"""
bilibili_api

哔哩哔哩的各种 API 调用便捷整合（视频、动态、直播等），另外附加一些常用的功能。

 (默认已导入所有子模块，例如 `bilibili_api.video`, `bilibili_api.user`)
"""

from . import (
    activity,
    app,
    article,
    article_category,
    ass,
    audio,
    audio_uploader,
    bangumi,
    black_room,
    channel_series,
    cheese,
    client,
    comment,
    creative_center,
    dynamic,
    emoji,
    favorite_list,
    festival,
    game,
    garb,
    homepage,
    hot,
    interactive_video,
    live,
    live_area,
    login_v2,
    manga,
    music,
    note,
    opus,
    rank,
    search,
    session,
    show,
    topic,
    user,
    video,
    video_tag,
    video_uploader,
    video_zone,
    video_zone_v2,
    vote,
    watchroom,
)
from .exceptions import (
    ApiException,
    ArgsException,
    CookiesRefreshException,
    CredentialNoAcTimeValueException,
    CredentialNoBiliJctException,
    CredentialNoBuvid3Exception,
    CredentialNoBuvid4Exception,
    CredentialNoDedeUserIDException,
    CredentialNoSessdataException,
    DanmakuClosedException,
    DynamicExceedImagesException,
    ExClimbWuzhiException,
    GeetestException,
    InitialStateException,
    LiveException,
    LoginError,
    NetworkException,
    ResponseCodeException,
    ResponseException,
    StatementException,
    VideoUploadException,
    WbiRetryTimesExceedException,
)
from .utils.aid_bvid_transformer import aid2bvid, bvid2aid
from .utils.anti_spider import get_bili_headers
from .utils.AsyncEvent import AsyncEvent
from .utils.danmaku import Danmaku, DmFontSize, DmMode, SpecialDanmaku
from .utils.geetest import Geetest, GeetestMeta, GeetestType
from .utils.high_level import (
    Api,
    Credential,
    bili_fast_download,
    bili_simple_download,
    configure_dynamic_fingerprint,
    ensure_bili_ticket,
    ensure_buvid,
    obtain_bili_ticket,
    obtain_buvid,
    recalculate_wbi,
)
from .utils.logger import request_log
from .utils.network import (
    BiliAPIClient,
    BiliAPIFile,
    BiliAPIResponse,
    BiliFilter,
    BiliFilterArgs,
    BiliFilterData,
    BiliFilterFlags,
    BiliFilterReturn,
    BiliWsMsgType,
    DelegateType,
    RequestSettings,
    clean_session,
    delegate,
    delegate_local_context,
    get_available_settings,
    get_client,
    get_delegates,
    get_exist_instances,
    get_force_settings,
    get_instance_settings,
    get_instances,
    get_registered_available_settings,
    get_registered_clients,
    get_registered_filters,
    get_selected_client,
    get_selected_instance,
    get_session,
    get_settings,
    new_instance,
    register_client,
    register_post_filter,
    register_pre_filter,
    remove_instance,
    request_settings,
    select_client,
    select_client_local_context,
    select_instance,
    select_instance_local_context,
    set_session,
    undelegate,
    unregister_client,
    unregister_filter,
    unset_session,
)
from .utils.parse_link import ResourceType, parse_link
from .utils.picture import Picture
from .utils.settings import bili_settings
from .utils.short import get_real_url
from .utils.sync import sync

BILIBILI_API_VERSION = "18.0.0.b1"


import importlib

from .clients import ALL_PROVIDED_CLIENTS

for module, client_name, settings in ALL_PROVIDED_CLIENTS[::-1]:
    try:
        importlib.import_module(module)
    except ModuleNotFoundError:
        continue
    register_client(
        module,
        getattr(
            importlib.import_module(
                name=f".clients.{client_name}", package="bilibili_api"
            ),
            client_name,
        ),
        settings,
    )

del ALL_PROVIDED_CLIENTS


__all__ = [
    "BILIBILI_API_VERSION",
    "Api",
    "ApiException",
    "ArgsException",
    "AsyncEvent",
    "BiliAPIClient",
    "BiliAPIFile",
    "BiliAPIResponse",
    "BiliFilter",
    "BiliFilterArgs",
    "BiliFilterData",
    "BiliFilterFlags",
    "BiliFilterReturn",
    "BiliWsMsgType",
    "CookiesRefreshException",
    "Credential",
    "CredentialNoAcTimeValueException",
    "CredentialNoBiliJctException",
    "CredentialNoBuvid3Exception",
    "CredentialNoBuvid4Exception",
    "CredentialNoDedeUserIDException",
    "CredentialNoSessdataException",
    "Danmaku",
    "DanmakuClosedException",
    "DelegateType",
    "DmFontSize",
    "DmMode",
    "DynamicExceedImagesException",
    "ExClimbWuzhiException",
    "Geetest",
    "GeetestException",
    "GeetestMeta",
    "GeetestType",
    "InitialStateException",
    "LiveException",
    "LoginError",
    "NetworkException",
    "Picture",
    "RequestSettings",
    "ResourceType",
    "ResponseCodeException",
    "ResponseException",
    "SpecialDanmaku",
    "StatementException",
    "VideoUploadException",
    "WbiRetryTimesExceedException",
    "activity",
    "aid2bvid",
    "app",
    "article",
    "article_category",
    "ass",
    "audio",
    "audio_uploader",
    "bangumi",
    "bili_fast_download",
    "bili_settings",
    "bili_simple_download",
    "black_room",
    "bvid2aid",
    "channel_series",
    "cheese",
    "clean_session",
    "client",
    "comment",
    "configure_dynamic_fingerprint",
    "creative_center",
    "delegate",
    "delegate_local_context",
    "dynamic",
    "emoji",
    "ensure_bili_ticket",
    "ensure_buvid",
    "favorite_list",
    "festival",
    "game",
    "garb",
    "get_available_settings",
    "get_bili_headers",
    "get_client",
    "get_delegates",
    "get_exist_instances",
    "get_force_settings",
    "get_instance_settings",
    "get_instances",
    "get_real_url",
    "get_registered_available_settings",
    "get_registered_clients",
    "get_registered_filters",
    "get_selected_client",
    "get_selected_instance",
    "get_session",
    "get_settings",
    "homepage",
    "hot",
    "interactive_video",
    "live",
    "live_area",
    "login_v2",
    "manga",
    "music",
    "new_instance",
    "note",
    "obtain_bili_ticket",
    "obtain_buvid",
    "opus",
    "parse_link",
    "rank",
    "recalculate_wbi",
    "register_client",
    "register_post_filter",
    "register_pre_filter",
    "remove_instance",
    "request_log",
    "request_settings",
    "search",
    "select_client",
    "select_client_local_context",
    "select_instance",
    "select_instance_local_context",
    "session",
    "set_session",
    "show",
    "sync",
    "topic",
    "undelegate",
    "unregister_client",
    "unregister_filter",
    "unset_session",
    "user",
    "video",
    "video_tag",
    "video_uploader",
    "video_zone",
    "video_zone_v2",
    "vote",
    "watchroom",
]
